package cn.xixitravel.ride.intent;

public enum TravelIntent {
    SEARCH_KNOWLEDGE,
    RIDE_QUOTE,
    RIDE_CREATE,
    RIDE_STATUS,
    RIDE_CANCEL,
    QUERY_NOTIFICATIONS,
    QUERY_INVOICE,
    LIST_MEMORY,
    SEARCH_MEMORY,
    REMEMBER_PREFERENCE,
    FORGET_PREFERENCE,
    CONFIRM_PENDING_ACTION,
    REJECT_PENDING_ACTION,
    UNKNOWN
}
