package cn.xixitravel.ride.task;

public enum TravelTaskObservationType {
    ROUTE_PROVIDED,
    QUOTE_RETURNED,
    QUOTE_SELECTED,
    CREATE_PREPARED,
    USER_CONFIRMED,
    USER_REJECTED,
    ORDER_CREATED,
    ORDER_STATUS_UPDATED,
    CANCEL_PREPARED,
    ORDER_CANCELLED,
    KNOWLEDGE_RETURNED,
    NOTIFICATIONS_RETURNED,
    INVOICE_ELIGIBILITY_RETURNED,
    MEMORY_ACTION_COMPLETED,
    TOOL_FAILED
}
