package cn.xixitravel.ride.task;

public enum TravelTaskPhase {
    NEEDS_CLARIFICATION,
    COLLECTING_ROUTE,
    READY_TO_QUOTE,
    WAITING_FOR_QUOTE_SELECTION,
    READY_TO_PREPARE_CREATE,
    WAITING_FOR_CREATE_CONFIRMATION,
    READY_TO_CREATE,
    WAITING_FOR_DISPATCH,
    COLLECTING_ORDER_ID,
    READY_TO_QUERY_STATUS,
    READY_TO_PREPARE_CANCEL,
    WAITING_FOR_CANCEL_CONFIRMATION,
    READY_TO_CANCEL,
    READY_TO_QUERY_NOTIFICATIONS,
    READY_TO_QUERY_INVOICE,
    READY_TO_SEARCH_KNOWLEDGE,
    READY_TO_LIST_MEMORY,
    READY_TO_SEARCH_MEMORY,
    READY_TO_REMEMBER_MEMORY,
    READY_TO_FORGET_MEMORY,
    COMPLETED,
    CANCELLED,
    FAILED
}
