package cn.xixitravel.ride.task;

public enum TravelTaskAction {
    ASK_FOR_CLARIFICATION,
    ASK_FOR_ROUTE,
    CALL_RIDE_QUOTE,
    ASK_FOR_QUOTE_SELECTION,
    CALL_RIDE_PREPARE_CREATE,
    ASK_FOR_CREATE_CONFIRMATION,
    CALL_RIDE_CREATE,
    WAIT_OR_QUERY_DISPATCH,
    ASK_FOR_ORDER_ID,
    CALL_RIDE_STATUS,
    CALL_RIDE_PREPARE_CANCEL,
    ASK_FOR_CANCEL_CONFIRMATION,
    CALL_RIDE_CANCEL,
    CALL_RIDE_NOTIFICATIONS,
    CALL_RIDE_INVOICE_ELIGIBILITY,
    CALL_TRAVEL_KNOWLEDGE_SEARCH,
    CALL_TRAVEL_MEMORY_LIST,
    CALL_TRAVEL_MEMORY_SEARCH,
    CALL_TRAVEL_MEMORY_REMEMBER,
    CALL_TRAVEL_MEMORY_FORGET,
    RESPOND_AND_STOP,
    STOP
}
